### ISSUE TITLE
Mobile Version: Menü wird nicht geöffnet, wenn ein Grundstück abgefragt wird

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#1]
Ich steh da auf dem Schlauch: ich habe versucht mit Helpers.openMenu() in extracts.service.js nach dem Laden des Extracts, aber dabei taucht das Menü nur kurz auf und verschwindet dann gleich wieder. @schmoker siehst du da einen einfachen Weg um das Menü im mobilen beim Laden eines neuen Extracts gleich aufgeklappt lassen? identisch mit #7

**Comment by schmoker** [comment]
Wurde mit Issue #7 behoben, stimmt das so?

**Comment by CoNussberger** [comment]
Ja dieser Issue ist identisch und kann somit wie #7 auch geschlossen werden
