### ISSUE TITLE
ID1186: Funtionalität ÖREB-Kataster als Reloa-Button besser herausheben

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#11]
ÖREB-Kataster-Logo: Funktion als Reload-Button ist nicht ausreichend erkennbar._x000D_
* Tooltip/Mousover erscheint sehr spät (Layout optimieren?)_x000D_
* Farbe ändern wenn Mousover

**Comment by bernhardsturm** [comment]
@CoNussberger bitte kontrollieren: ich habe jetzt ein Reload-Icon neben das Logo gesetzt. Das sollte klappen, was meinst du?

**Comment by CoNussberger** [comment]
So ist es schon fast etwas zu prominent. 
Hab mich kurz intern abgesprochen. Wir sind zum Schluss gekommen. 
1. Rückgängig machen.
2. Issue als Wontfix schliessen

**Comment by bernhardsturm** [comment]
Wird nicht realisiert.
