### ISSUE TITLE
ID1187: Funktionalität Headermitte (Grundstück Nr.) ergänzen

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#12]
Die Anzeige des aktuell geladenen Grundstücks in der Header-Mitte könnte auch ein Direktlink_x000D_ sein, um die Karte wieder in den Bereich des Grundstücks zu zoomen.

**Comment by bernhardsturm** [comment]
Oder sollen wir dazu ein neues Icon machen? @CoNussberger was meinst du? Sonst ist das etwas kryptisch und funktioniert nur im Desktop...

**Comment by CoNussberger** [comment]
Wo würde das Icon dann erscheinen? Auch im Header oder würdest du das Ikon an einem anderen Ort platzieren?

**Comment by bernhardsturm** [comment]
Ich würde es als Applikations-Icon machen. So:

![2018-11-26 13_29_06-oreb - smartauszug _ application cadastre rdppf](https://user-images.githubusercontent.com/16875426/49014404-4de8a400-f180-11e8-8b37-9da46d41a8b4.png)

**Comment by CoNussberger** [comment]
Die Idee mit dem Icon finde ich gut. Wärs möglich die Funktionalität gleichzeitig im Icon und auf der Desktopversion auch in der Headermitte zu haben? Ich fänd das noch elegant.

**Comment by bernhardsturm** [comment]
@schmoker Könntest du in map.html auf Zeile 40 noch eine Angular-Funktion zum zentrieren auf das aktive Grundstück einbauen: 

`    
    <button class="button svg-icon btnCenterObject" ng-click="map.centerObject()">
            <svg class="icon icon-zoomToCenter">
                <use xlink:href="#icon-zoomToCenter"></use>
            </svg>
    </button>`

**Comment by schmoker** [comment]
Ist integriert, bitte überprüfen.

**Comment by bernhardsturm** [comment]
@CoNussberger Bitte diese Funktion prüfen und schliessen, falls ok.

**Comment by CoNussberger** [comment]
Funktioniert
