### ISSUE TITLE
ID1189: Fehlermeldungen optimieren

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#14]
Insbesondere wenn für einen Ort kein EGRID gefunden werden kann, ist das Verhalten noch nicht optimal. Siehe z.B. Gemiende Lüscherz. Analyse wann welche Fehlermeldung Ausgegeben wird. Optimierungsmöglichkeiten ermitteln. Optimierungen umsetzen.

**Comment by schmoker** [comment]
Anstelle eines leeren Ergebnis (siehe Bild) zeigen wir hier "Leider haben wir keine weiteren Daten zu diesem Grundstück gefunden?". Passt das?

![image](https://user-images.githubusercontent.com/3541431/49507201-3eecaa80-f880-11e8-8c2b-f3b007526be2.png)

**Comment by CoNussberger** [comment]
Könntest du bitte den folgenden Text vorsehen:
Deutsch
_Für dieses Grundstücke kann keine Auswertung erstellt werden, da die Daten der amtlichen Vermessung nicht in ausreichender Qualität vorliegen._ 

Französisch:
_Ce bien-fonds se situe à l'extérieur des zones disposant d'une  Mensuration Officielle de qualité suffisante, il n'est pas possible démarrer l'évaluation:._

**Comment by bernhardsturm** [comment]
@CoNussberger könntest du das prüfen, und danach schliessen?
