### ISSUE TITLE
ID1191: Link  Amt für Geoinframtion in zusätzlichem Fenster öffnen

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#15]
Der Link zum «Amt für Geoinformation» im Impressum soll in einem neuen Tab_x000D_
geöffnet werden.

**Comment by bernhardsturm** [comment]
Oha... der ist nicht mal richtig als Link erkennbar. Ich korrigiere das auch noch.

**Comment by bernhardsturm** [comment]
Ist umgesetzt. Bitte @CoNussberger testen.

**Comment by CoNussberger** [comment]
Ist in Ordnung
