### ISSUE TITLE
ID1192: Gösse Header-Balken Desktopversion

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#16]
Der Header-Balken wird auf dem Desktop höher und nimmt somit wertvollen Platz ein, was_x000D_ bei der Bedienung mit der Maus keinen Vorteil bringt.

**Comment by bernhardsturm** [comment]
@CoNussberger Bitte kontrollieren, ist korrigiert.

**Comment by CoNussberger** [comment]
Habe es kontrolliert, ist in Ordnung.
