### ISSUE TITLE
ID1193: Sprachumschaltung umplatzieren

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#17]
Die Sprachumschaltung benötigt kostbaren Platz im oberen Teil des Menüs (Tablet). Siehe Studie von U5

**Comment by bernhardsturm** [comment]
@CoNussberger das gibt mir ein wenig Probleme... Wo wollen wir die umplatzieren, ohne dass französischsprachige User gleich überall suchen müssen? Normalerweise ist die Sprachnavi immer oben.

**Comment by CoNussberger** [comment]
In der Desktop Version würde ich das Sprachnavi auf jeden Fall oben belassen. In der "mobilen" Version gibt es durchaus auch andere Applikationen, die dann das Spachnavi nach unten verschieben. Siehe z.B. auch map.geo.admin.ch 
Auch bei Google-Maps ist das Sprachnavi unten (hier selbst, wenn man es auf dem Desktop benutzt).

**Comment by bernhardsturm** [comment]
Die Sprachnavi ist jetzt für die mobile Version ganz unten. Bitte überprüfen.

**Comment by CoNussberger** [comment]
Ist so in Ordnung. Beim Prüfen ist mir Aufgefallen, dass die "Vorhergeladenen Grundstücke" seit der Anpassungen am Menü nicht mehr angezeit werden, wenn kein Grundstück geladen ist. @bernhardsturm könntest du das bitte wieder koorigieren.

**Comment by bernhardsturm** [comment]
Oh ja. Das ging verloren. Jetzt ist die History wieder drinn. Bitte nochmals prüfen.

**Comment by CoNussberger** [comment]
Jetzt passts.
