### ISSUE TITLE
ID1198: Grundbuchkreisname in Header ergänzen

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#19]
Der Grundbuchkreisname soll im oberen Bereich des Menüs zusätzlich angezeigt werden. Bei erarbeitung Beachten, dass es Kreise gibt, die gleich heissen wie die Gemeinde selber.

**Comment by bernhardsturm** [comment]
Das ist mal gesetzt. Testen mit Grundstück CH894676623553. Allerdings teste ich noch nicht auf identischen Gemeindename. Das mache ich auch noch.

**Comment by bernhardsturm** [comment]
@CoNussberger ist umgesetzt und kann hier getestet werden: 

http://oerebdev19.stubr-dev.ch/#/d/CH894676623553

**Comment by CoNussberger** [comment]
@bernhardsturm  Das funktioniert soweit gut, ich hätte aber noch einen Verbesserungsvorschlag:
Damit wir etwas Text sparen können, würde ich vorschlagen, dass wir in Anlehnung an die zweite Seite des PDF-Auszugs die folgende Form wählen könnten:

`Geladenes Grundstück: 741 in Bern,
4-Kirchenfeld, Schlosshalde`

Was meinst du dazu?

**Comment by bernhardsturm** [comment]
Das habe ich so gemacht. Viel schöner.

**Comment by CoNussberger** [comment]
So passts. Den test für die identischen Namen von Gemeinde und Kreis musst du nicht umsetzen. Haben gesehn, dass wir das beireits beim erstellen des XML abfangen. Wenn die Namen identisch sind, wir gar kein Kreis abgefüllt.

Somit ist dieser Issue für mich erledigt.
