### ISSUE TITLE
ID1199: Verhalten Menü bei beim erneuten Aufrufen eines Grundstücks optimieren

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#20]
Mobil: Sofern Daten eines Grundstücks geladen sind und das Menü geschlossen ist, sollte ein erneutes Tippen auf den in der Info-Box enthaltenen Link zum Laden der Daten eines Grundstücks das Menü wieder öffnen. 
Immer: Markierung (orange) des Grundstücks und das Dialogfeld müssen wieder verschwinden.

**Comment by bernhardsturm** [comment]
@CoNussberger ist umgesetzt, könntest du das testen?

**Comment by CoNussberger** [comment]
Die orange Markierung des Grundstücks verschwindet noch nicht. (Nur das Dialogfeld)
Muss noch angepasst werden

**Comment by schmoker** [comment]
Bitte erneut überprüfen.

**Comment by CoNussberger** [comment]
Jetzt passts
