### ISSUE TITLE
ID1200: Loading Symbol optimieren

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#21]
Mögliche Vorlagen ÖREB-Kataster Kanton Baselland oder Uri

**Comment by bernhardsturm** [comment]
@CoNussberger was ist hier der Wunsch? Bei den Beispielen aus Baselland und Uri komme ich nicht so richtig in die Gänge: bei Uri ist es eine ganze Fabrik die da animiert wurde und in Baselland kommt ein Spinner (drehendes Rad) mit einem Text. Was wäre gewünscht?

**Comment by CoNussberger** [comment]
Könntest du mal einen Spinner ausprobieren. So was ähnliches wie in den Geoportalkarten (Spinner im Zentrum des Bildes wenn die Karte nachlädt) wär denke ich nicht. Schlecht. Für den Anfang würd ichs mal mit Graustufen ausprobieren. Hilft diese Spezifizieurng weiter?

**Comment by bernhardsturm** [comment]
Okay... ja ich versuche das mal, ich glaube, ich weiss, was du meinst.

**Comment by bernhardsturm** [comment]
Jetzt habe ich mal was. Aber ich bin nicht sicher, ob es das ist, was du gesucht hast. Es ist jetzt so ein klassischer Loader-Spinner. Kannst du das mal kontrollieren @CoNussberger ? (http://oerebdev19.stubr-dev.ch)

**Comment by CoNussberger** [comment]
Das ist für uns so in Ordnung.
