### ISSUE TITLE
# 1338 Probleme mit Transparenz der Layer der Eigentumsbeschränkungen

### ISSUE THREAD

**Issue by CoNussberger** [kanton-bern/oerebViewer#24]
Wenn auf einem Grundstück mehrere Eigentumsbeschränkungen (Flächen, Punkte, Linien) des gleichen Themas resp. Subthemas bei der Nutzungsplanung liegen, so wird im ÖREB-Viewer der WMS-Layer mehrfahr eingeblendet. Durch die mehrfache Überlagerung wrid die Transparenz abgeschwächt und geht nach ca. 3 Objekten ganz verloren.

Der ÖREB-Viewer muss so erweitert werden, dass identische Layer innerhalb eines Themas resp. Subthemas in der Karte nur 1x eingebunde werden.

(Ganz unschön ist das Phänomen bei den Bauklassen der Stadt Bern, da dort z.T. die Labels mehrfach dargestellt und abgeschnitten werden. Bsp: https://oerebview.apps.be.ch/#!/d/CH950546763529)

**Comment by bernardkessler** [comment]
Das Phänomen mit den sich überlagernden Labels lag daran, dass der WMS als TILED eingebunden war und die Labels pro Kachel statt pro Objekt dargestellt und teilweise am Kachelrand auch abgeschnitten wurden. 

Das Problem wurde nun behoben, indem der WMS nicht mehr in Kacheln aufgetrennt eingebunden wird.
