### ISSUE TITLE
#1180 - Neue Weisungen Webservice und DATA-Exctract

### ISSUE THREAD

**Issue by CoNussberger** [kanton-bern/oerebViewer#26]
Es muss die Weisungsversion vom 01. Novermber 2017 der Weisung DATA-Extract und Webservice umgesetzt werden.

Von der Weisungsänderung des Webservices ist insbesondere der Aufrufg von getEGRID() betroffen. Dieser muss minimal angepasst werden.

Mit der neuen Version des DATA-Extract wurde der XML resp. JSON-Auszug überarbeitet.

Beispiele-Auszüge (JSON) von ausgewählten Grunstücken im Kanton Bern werden per Mitte März zur Verfügung stehen.

**Comment by bernardkessler** [comment]
Folgende Anpassungen sind noch nötig:

- Kantonale und nationale Themen: "Vollständige Legende herunterladen ()" funktioniert nicht
- Kantonale und nationale Themen: "Gesetzliche Grundlagen" sowie "Weitere Informationen und Hinweise" fehlen
- Vorher geladene Grundstücke: Gemeindewappen fehlen
- Legenden: Die Legendeneinträge sollen nach absteigender Fläche/Länge/Anzahl Punkte und bei Gleichstand alphabetisch sortiert werden

**Comment by bernardkessler** [comment]
**Erledigt:**
- "Vollständige Legende herunterladen" funktioniert
- Gemeindewappen von vorher geladenen Grundstücken erscheint
- Legendeneinträge werden korrekt nach absteigender Grösse und bei Gleichstand alphabetisch sortiert

**ToDo:**
- "Gesetzliche Grundlagen", "Rechtsvorschriften" und "Weitere Informationen und Hinweise" fehlen in allen Themen

**Comment by bernardkessler** [comment]
Die Gesetzlichen Grundlagen erscheinen nun überall.
