### ISSUE TITLE
Dokumentation: Eventuell Bedienungsanleitung integrieren

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#27]
**Interne Anleitung**
Die interne Anleitung wird direkt als eigener Menüpunkt ins Hauptmenü integriert. Dort kann man via HTML-Seiten (analog Impressum) mit Bilder und Dokumentation die Bedienung des OEREBViewers beschreiben. Konfiguration könnte über die Sprachfiles (komplex) oder direkt durch die Anpassung der entsprechenden HTML-Seiten erfolgen.

**Externe Anleitung**
Alternative wäre: die Anleitung wird auf einer externen Ressource gehostet (PDF / HTML) und kann via Link aus dem OEREBViewer aufgerufen werden.

**Comment by bernardkessler** [comment]
Ein Link auf eine externe Anleitung wäre tatsächlich noch eine gute Idee, hatte ich zwischenzeitlich leider nicht mehr auf dem Schirm.

Am besten sollte sich der Link via Config ein- oder ausblenden lassen und permanent zur Verfügung stehen, also auch, wenn noch kein Grundstück ausgewertet wurde. Beim Link kann es sich um ein passendes Icon, einen Text oder eine Kombination aus beidem handeln, je nachdem, was sich gut umsetzen lässt und nutzerfreundlich erscheint.

**Comment by sheggi** [comment]
Sobald die `instructionUrl` gesetzt ist, wird neu ein Link unten links angezeigt.

```
/**
 * External Instructions
 * ---------------------
 * provides url for visiting external instructions
 */
export const externalInstructions = {
  instructionUrl: 'https://example.com/to/external/instructions.html', // url to external instruciton - disabled if false
}
```

![Screenshot 2022-07-06 at 13 01 43](https://user-images.githubusercontent.com/7480753/177536070-cddf2fd7-3661-4670-a5dd-f5590158fd9d.png)

**Comment by bernardkessler** [comment]
Sieht schon sehr gut aus, aber noch zwei Fragen:

1. Wäre es möglich, dass der Link in einer neuen Registerkarte geöffnet wird, wie z.B. bei der Verlinkung auf's Geoportal?
2. Wäre es möglich, dass auch bei dieser URL mit dem placeholder {{language}} und {{languageUppercase}} gearbeitet werden kann?
