### ISSUE TITLE
Konfiguration der Suchfunktion

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#29]
**Suchfunktion ist komplex zum Einbauen**
Wäre es möglich in der Definition der Suchfunktion zwei Alternativen zu hinterlegen? Also einmal hätte man die eingebaute Suche des Kantons Bern und dann die etwas ungenaue der Landestop. Könnte man das mit Aus- oder Einkommentieren lösen?

**Comment by sheggi** [comment]
Kann bei Bedarf wieder geöffnet werden.
