### ISSUE TITLE
User und Passwort für geschütze Dienste BE anpassen

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#3]
Bisher wird für die geschützten Kartendienste noch das Test-Passwort aus dem Aufbau verwendet. Neu sollen ein permaneter User und Passwort eingesetzt werden. Für die notwendigen Informationen bitte bei mir melden.

**Comment by schmoker** [comment]
Die Zugangsdaten müssen beim builden in die .env Datei geschrieben werden: 

```
TOKEN_USERNAME=user_example
TOKEN_PASSWORD=password_example
```

Können wir diesen Task somit abschliessen?

**Comment by CoNussberger** [comment]
Wär es möglich das für eure Umgebung (oerebdev19.stuber-dev ) umzusetzen, sodass ich das testen kann?
