### ISSUE TITLE
PDF-Auszug auf ÖREB-Server umstellen

### ISSUE THREAD

**Issue by bernardkessler** [kanton-bern/oerebViewer#37]
Der PDF-Auszug soll nun durch den ÖREB-Server erstellt werden. Nötige Anpassung:

oerebViewer/src/app/components/config/config.service.js
// Basis URL des OEREB-Webservice gemäss Weisung

pdf: 'https://www.oereb2.apps.be.ch/OerbverSVC.svc',
ersetzen durch
pdf: 'https://www.oereb.apps.be.ch',

**Comment by bernhardsturm** [comment]
Ist umgesetzt. Bitte beim nächsten Build prüfen.
