### ISSUE TITLE
Schreibfehler korrigieren

### ISSUE THREAD

**Issue by bernardkessler** [kanton-bern/oerebViewer#39]
Bitte folgende Textstellen korrigieren:

**Deutsch + Französisch:**
- Im Impressum unter "Grundlagendaten" steht nach dem Datum ein unnötiges "22y"

**Französisch:**
- "Aucune bein-fonds chargé!" ersetzen durch "Aucun bien-fonds sélectionné"
- "Naviguez sur le bein-fonds souhaitée et démarrez l'évaluation." ersetzen durch "Naviguez sur le bien-fonds souhaité et démarrez l'analyse."
- "Historique des bien-fonds chargése" ersetzen durch "Historique des biens-fonds chargés"
- wenn man ein Grundstück gesucht hat und die Auswertung starten soll (im kleinen Popup) -> "Démarrer l'évaluation" ersetzen durch "Démarrer l'analyse"

**Comment by bernhardsturm** [comment]
Bitte beim nächsten Release testen und schliessen wenn gut.
