### ISSUE TITLE
Parzellenumrandung entspricht nicht der neuen Weisung

### ISSUE THREAD

**Issue by bernardkessler** [kanton-bern/oerebViewer#72]
Bei der Abnahme unseres PDF-Auszugs wurde durch den Bund bemängelt, dass die rote Parzellenumrandung nicht den neuen Vorgaben in der überarbeiteten Weisung entspricht. Da in der Weisung steht, dass die Vorgaben soweit möglich auch für den dynamischen Auszug gelten, möchten wir die Parzellenumrandung auch im ÖREB-Viewer anpassen.

Die neuen Werte für die rote Umrandungslinie lauten:
fillColor: "#ff0000"
fillOpacity: 0.0
strokeColor: "#e60000"
strokeOpacity: 0.60
strokeWidth: 5

Bei Fragen bitte melden. Abrechnung via Supportbudget. Die Umsetzung ist wahrscheinlich nicht super dringend, aber am besten sobald möglich. Ob eine konkrete Frist besteht, ist noch in Abklärung und wird ggf. nachgeliefert.

**Comment by sheggi** [comment]
Diese Werte werden gleich als Standardwerte übernommen, können jedoch auch mit eigenen Settings überschrieben werden.

![Screenshot 2022-08-31 at 14 03 54](https://user-images.githubusercontent.com/7480753/187674229-51f0034d-29df-40fe-8ef6-893147f78efb.png)

**Comment by sheggi** [comment]
Standardwerte sind hier definiert

https://github.com/kanton-bern/oerebViewer/blob/55ccf83ca56d3f677b42a9a76c3af8defc3890ad/config/defaults/setup.js#L132
