### ISSUE TITLE
ID1183: Informationsgehalt Menü vor Auswertung ergänzen

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#8]
Falls das Menü leer geöffnet wird (also bevor Daten eines Grundstücks geladen werden), einen Hinweis im Menü anzeigen, dass zuerst ein Grundstück gesucht und dessen Daten_x000D_ geladen werden sollen.

**Comment by schmoker** [comment]
Was für einen Text soll ich hier anzeigen? @CoNussberger

**Comment by CoNussberger** [comment]
Es müssten zwei Textbestandteile sein. 
1. `Kein Grundstück geladen!`
2. `Navigieren Sie zum gewünschten Grundstück und starten Sie die Auswertung.`

(Die Übersetzung fürs Französische liefere ich noch nach)

Evtl. Könnten wir auch noch den Link auf die Kurzanleitung hinzufügen. Diese erreicht Ihr unter http://www.geo.apps.be.ch/de/oereb-kataster-4/anleitung-nutzung.html . 

@bernhardsturm was meinst du dazu?

Für die Gestaltung könntet Ihr euch am Vorschlag von U5 auf der zweitletzten Seite des Usability-Berichts orientieren. Das Bild brauchts meines Erachtens aber nicht.
[UsabilityTest-2_öreb_2017_Bericht.pdf](https://github.com/kanton-bern/oerebViewer/files/2662654/UsabilityTest-2_oreb_2017_Bericht.pdf)

**Comment by CoNussberger** [comment]
Hier noch die französische Übersetzung:
1. `Aucune bein-fonds chargé!`
2. ` Naviguez sur le bein-fonds souhaitée et démarrez l'évaluation.`
