### ISSUE TITLE
ID1184: Menü-Struktur verbessern

### ISSUE THREAD

**Issue by bernhardsturm** [kanton-bern/oerebViewer#9]
* Die Zeilenhöhe im Menü ist für die Fingerbedienung auf dem Tablet eher knapp, diese_x000D_
sollte nach gängigen Empfehlungen mindestens 40 Pixel betragen._x000D_
* Anzahl betroffene ÖREB-Anzeigen_x000D_
* Menüeinträge besser hervorheben_x000D_
Siehe auch Analyse U5 und evtl. Portal Kanton Baselland

**Comment by bernhardsturm** [comment]
Pixel-Höhe ist angepasst

**Comment by bernhardsturm** [comment]
@CoNussberger kannst du mal das menü mit der Anzeige der betroffenen Themen anschauen? Ich mache dann noch einen alternativen Gestaltungsvorschlag für die Menüs

**Comment by CoNussberger** [comment]
Die Pixel-Höhe finde ich so viel besser. 
Die Kreise mit den Zählern drin würde ich eher rechts neben dem +/- für das Auf- und Zuklappen platzieren.
Direkt nach dem Aufrufen des Grundsütcks ist ja der Menüeintrag "Aktive ÖREB-Themen" aufgeklappt und somit aktiv. Ich denke es wär gut wenn dieser  direkt nach dem Auswerten des Grundstücks dunkelgrau markiert würde. 
**Achtung** noch beim zählen der aktiven Themen. Es müssen die Themen gezählt werden und nicht die Subthemen. Sonst stimmt die Anzahl nicht mit dem überein was auf der 2. Menüstufe angezeigt wird.

**Comment by bernhardsturm** [comment]
@CoNussberger könntest du es nochmals anschauen? ich habe jetzt die etwas unwichtigeren Menüpunkte etwas zurückgenommen. Sonst müsste ich etwas radikaler umgestalten.

**Comment by bernhardsturm** [comment]
@CoNussberger kannst du das menü nochmals prüfen?

**Comment by CoNussberger** [comment]
So finde ich es viel besser. Jetzt ist die Hirarchie doch deutlich besser erkennbar. 
Ein paar Sachen sind mir noch aufgefallen:
* In der mobilen Version ist die Schriftgrösse bei der 2. und 3. Menüebene nicht kleiner. Ist dies Absicht.? Ich denke es wär gut, wenn sich hier Mobil und Desktop gleich verhalten.
*  Wärs evtl. möglich in den Menüpunkten "Das Grundstück nicht betreffende ÖREB-Themen" und  "Nicht vorhandene ÖREB-Themen" bei der Auflistung der Themen zwischen den einzlnen Themen auch Trennlinien einzufügen oder wär das sehr aufwendig?
* Bei Menü, Geladenes Grundstück und der Grundstücks-Nr. in der Headermitte wird die Schrift in der mobilen Version nicht schön dargestellt (siehe Abbildung). Könnte das evtl. mit der Schriftgrösse zusammenhängen. In der aktuellen Version (oerebview.apps.be.ch) wars bei allen Schriften der Fall jetzt nur noch bei den oben erwähnten.
![darstellungschrift](https://user-images.githubusercontent.com/23398143/50077176-ef916d00-01e3-11e9-8a3b-e0f5088357c5.PNG)
* Im Moment gibts wieder keine Hintergrundbilder. 

Könntest du bitte schauen ob bei den erwähnten Punkten noch Optimierungen möglich sind.

**Comment by bernhardsturm** [comment]
@CoNussberger jetzt sollten die Punkte alle realisiert sein. Kannst du es nochmals prüfen?

**Comment by CoNussberger** [comment]
* Die ersten beiden Punkte sind in Ordnung. 
* Die Schrift im Header ist immer noch nicht ganz "rund" (siehe Graphik)
* Ich habe immer noch keinen Hintergrund

![darstellungschriftkopfzeile](https://user-images.githubusercontent.com/23398143/50086648-ff1daf80-01fd-11e9-8777-005c1c74fffd.PNG)

**Comment by bernhardsturm** [comment]
Ja der Header: das mache ich noch. Hintergrund, ist wohl, dass ich jedes mal meine .env auch auf dem Server überschreibe. Schlecht und mache ich nicht mehr. @schmoker könntest du nochmals deine .env auf den Server setzen?

**Comment by bernhardsturm** [comment]
@CoNussberger Kannst du es nochmals testen? Ich habe jetzt das Font-Rendering etwas optimiert. Auch ist der Hintergrund wieder da.

**Comment by CoNussberger** [comment]
Für mich ist es jetzt in Ordnung.
